access_key       = "YOUR_AWS_API_KEY"
secret_key       = "YOUR_AWS_SECRET_KEY"
alexa_skill_id   = "YOUR_DEV_ALEXA_SKILL_ID"
function_version = "$LATEST" # "1"
region           = "YOUR_CHOSEN_REGION"
environment      = "dev"
alexa_skill_id   = ""
function_version = "$LATEST"